"""Startup-discovered adaptive kernel regression context indicator."""

from __future__ import annotations

from aef_terminal.indicators.control_specs import _control
from aef_terminal.indicators.module_contract import IndicatorModule, IndicatorSpec
from aef_terminal.indicators.runtime import (
    IndicatorExecutionSpec,
    IndicatorRunContext,
)

from .calculation import adaptive_kernel_regression
from .contracts import (
    ADAPTIVE_KERNEL_CALCULATION_MODES,
    ADAPTIVE_KERNEL_LABEL_ANCHORS,
    ADAPTIVE_KERNEL_LABEL_ANCHOR_OPTIONS,
    ADAPTIVE_KERNEL_REGRESSION_VERSION,
    EVENT_FIELDS,
    SERIES_COMPACT_FIELDS,
    SERIES_FIELDS,
    AdaptiveKernelRegressionParams,
    build_params,
)


INDICATOR_MODULE = IndicatorModule(
    IndicatorSpec(
        "adaptive_kernel_regression",
        "Adaptive Kernel Regime",
        "causal Gaussian kernel, residual bands, confirmed history and optional provisional tail",
        {
            "version": ADAPTIVE_KERNEL_REGRESSION_VERSION,
            "series": [],
            "events": [],
            "latest": None,
            "plan": None,
            "overlays": [],
            "signals": [],
        },
        "adaptiveKernelRegression",
        ("aef_terminal.indicators.modules.adaptive_kernel_regression:adaptive_kernel_regression"),
        group="primary",
        pipeline_stage="primary",
        pipeline_order=20,
        candidate_promoter="none",
        paper_tradable=False,
        custom_renderer=True,
        renderer_kind="custom",
        renderer_ref="adaptive_kernel_regression_series",
        renderer_primitives=("custom", "label", "line", "marker", "table"),
        renderer_placements=("price", "table"),
        custom_renderer_requirements=(
            "price_overlay_provider",
            "indicator_state_series_v1",
            "candle_style_provider",
            "shared_linear_gradient",
        ),
        renderer_table_label="KERNEL",
        table_contract="indicator-table-v1",
        overlay_layer="levels",
        overlay_filter_ref="adaptive_kernel_regression_filter",
        score_family="trend",
        empirical_power=0.75,
        usefulness=0.90,
        module_type="context",
        state_key="adaptiveKernelRegression",
        calc_key="adaptiveKernelRegressionCalcEnabled",
        visible_key="adaptiveKernelRegressionVisible",
        chart_control_id="adaptive-kernel-regression-toggle",
        process_control_id="adaptive-kernel-regression-process",
        api_enabled_key="adaptive_kernel_regression_enabled",
        api_visible_key="adaptive_kernel_regression_visible",
        manager_order=20,
        runtime_order=20,
        default_calc=False,
        default_visible=True,
        runtime_payload_contract={
            "latest": SERIES_FIELDS,
            "series": SERIES_FIELDS,
            "events": EVENT_FIELDS,
        },
        runtime_payload_schema_refs=("overlay_contract",),
        runtime_payload_compact_contract={
            "series": SERIES_COMPACT_FIELDS,
        },
        runtime_payload_compact={
            "series": {"limit": 240, "fields": "compact_contract"},
            "events": {"limit": 80, "fields": "runtime_contract"},
            "overlays": {"limit": 83, "fields": "compact_contract"},
        },
        controls=(
            _control(
                "calculationMode",
                "State",
                "select",
                "confirmed",
                "adaptiveKernelCalculationMode",
                element_id="adaptive-kernel-calculation-mode",
                api_key="adaptive_kernel_calculation_mode",
                param_key="calculation_mode",
                options=ADAPTIVE_KERNEL_CALCULATION_MODES,
                action="load_apply",
            ),
            _control(
                "visualMode",
                "Visual Mode",
                "select",
                "bands",
                "adaptiveKernelVisualMode",
                element_id="adaptive-kernel-visual-mode",
                options=("bands", "single", "trail"),
                option_labels=("Bands", "Single Line", "Trail"),
                action="render",
            ),
            _control(
                "theme",
                "Theme",
                "select",
                "Classic",
                "adaptiveKernelTheme",
                element_id="adaptive-kernel-theme",
                options=(
                    "Classic",
                    "Cyber Aqua",
                    "Crimson Pulse",
                    "Royal Purple",
                    "Emerald Night",
                    "Minimal Mono",
                    "Classic Emerald",
                ),
                action="render",
            ),
            _control(
                "candles",
                "Color Bars",
                "toggle",
                True,
                "adaptiveKernelCandles",
                element_id="adaptive-kernel-candles",
                action="render",
                compact=True,
            ),
            _control(
                "fill",
                "Fill Bands",
                "toggle",
                True,
                "adaptiveKernelFill",
                element_id="adaptive-kernel-fill",
                action="render",
                compact=True,
            ),
            _control(
                "textSize",
                "Text size",
                "select",
                "medium",
                "adaptiveKernelTextSize",
                element_id="adaptive-kernel-text-size",
                options=("small", "medium", "large"),
                action="render",
            ),
            _control(
                "labelAnchor",
                "Label Anchor",
                "select",
                "main",
                "adaptiveKernelLabelAnchor",
                element_id="adaptive-kernel-label-anchor",
                api_key="adaptive_kernel_label_anchor",
                param_key="label_anchor",
                options=ADAPTIVE_KERNEL_LABEL_ANCHORS,
                option_labels=ADAPTIVE_KERNEL_LABEL_ANCHOR_OPTIONS,
                action="load_apply",
            ),
            _control(
                "labelOffsetMult",
                "Offset Mult (ATR)",
                "number",
                0.5,
                "adaptiveKernelLabelOffsetMult",
                element_id="adaptive-kernel-label-offset-mult",
                api_key="adaptive_kernel_label_offset_mult",
                param_key="label_offset_mult",
                minimum=0.0,
                maximum=3.0,
                step=0.05,
                action="load_apply",
            ),
            _control(
                "dashboard",
                "Show Dashboard",
                "toggle",
                True,
                "adaptiveKernelDashboard",
                element_id="adaptive-kernel-dashboard",
                action="render",
                compact=True,
            ),
            _control(
                "entryPlan",
                "Entry Plan",
                "toggle",
                False,
                "adaptiveKernelEntryPlan",
                element_id="adaptive-kernel-entry-plan",
                api_key="adaptive_kernel_entry_plan_enabled",
                param_key="entry_plan_enabled",
                action="load_apply",
                compact=True,
            ),
            _control(
                "lookbackWindow",
                "Lookback Window",
                "number",
                30,
                "adaptiveKernelLookbackWindow",
                element_id="adaptive-kernel-lookback-window",
                api_key="adaptive_kernel_lookback_window",
                param_key="lookback_window",
                minimum=10,
                maximum=300,
                step=1,
                action="load_apply",
            ),
            _control(
                "baseBandwidth",
                "Base Bandwidth (h)",
                "number",
                8,
                "adaptiveKernelBaseBandwidth",
                element_id="adaptive-kernel-base-bandwidth",
                api_key="adaptive_kernel_base_bandwidth",
                param_key="base_bandwidth",
                minimum=0.5,
                maximum=64.0,
                step=0.5,
                action="load_apply",
            ),
            _control(
                "adaptiveBandwidth",
                "Adaptive Bandwidth (ATR-scaled)",
                "toggle",
                True,
                "adaptiveKernelAdaptiveBandwidth",
                element_id="adaptive-kernel-adaptive-bandwidth",
                api_key="adaptive_kernel_adaptive_bandwidth",
                param_key="adaptive_bandwidth",
                action="load_apply",
            ),
            _control(
                "atrLen",
                "ATR Length (adaptive)",
                "number",
                14,
                "adaptiveKernelAtrLen",
                element_id="adaptive-kernel-atr-len",
                api_key="adaptive_kernel_atr_len",
                param_key="atr_len",
                minimum=5,
                maximum=100,
                step=1,
                action="load_apply",
            ),
            _control(
                "outputSmoothing",
                "MA Output Smoothing",
                "number",
                3,
                "adaptiveKernelOutputSmoothing",
                element_id="adaptive-kernel-output-smoothing",
                api_key="adaptive_kernel_output_smoothing",
                param_key="output_smoothing",
                minimum=1,
                maximum=20,
                step=1,
                action="load_apply",
            ),
            _control(
                "bandMultiplier",
                "Band Multiplier (σ)",
                "number",
                1,
                "adaptiveKernelBandMultiplier",
                element_id="adaptive-kernel-band-multiplier",
                api_key="adaptive_kernel_band_multiplier",
                param_key="band_multiplier",
                minimum=0.5,
                maximum=5.0,
                step=0.1,
                action="load_apply",
            ),
            _control(
                "bandLookback",
                "Band Lookback (σ)",
                "number",
                24,
                "adaptiveKernelBandLookback",
                element_id="adaptive-kernel-band-lookback",
                api_key="adaptive_kernel_band_lookback",
                param_key="band_lookback",
                minimum=10,
                maximum=200,
                step=1,
                action="load_apply",
            ),
            _control(
                "bandSmoothing",
                "Band Smoothing",
                "number",
                5,
                "adaptiveKernelBandSmoothing",
                element_id="adaptive-kernel-band-smoothing",
                api_key="adaptive_kernel_band_smoothing",
                param_key="band_smoothing",
                minimum=1,
                maximum=20,
                step=1,
                action="load_apply",
            ),
        ),
    ),
    adapter_ref=("aef_terminal.indicators.modules.adaptive_kernel_regression:build_execution_spec"),
    params_builder_ref=("aef_terminal.indicators.modules.adaptive_kernel_regression:build_params"),
    ui_js_assets=("client.js",),
)


def build_execution_spec(ctx: IndicatorRunContext) -> IndicatorExecutionSpec:
    calculate = adaptive_kernel_regression
    params = ctx.params("adaptive_kernel_regression")
    if not isinstance(params, AdaptiveKernelRegressionParams):
        raise TypeError(
            "adaptive_kernel_regression runtime params must be AdaptiveKernelRegressionParams"
        )
    preview_bars = (
        ctx.live_signal_bars
        if (
            params.calculation_mode == "provisional"
            and ctx.live_preview_active
            and ctx.live_signal_bars
        )
        else ()
    )
    return IndicatorExecutionSpec(
        id="adaptive_kernel_regression",
        input_bars=ctx.confirmed_bars,
        analysis_bar=ctx.analysis_latest,
        mode="confirmed",
        calculate=lambda: calculate(ctx.confirmed_bars, params=params),
        preview_calculate=(
            (lambda: calculate(preview_bars, params=params, preview_only=True))
            if preview_bars
            else None
        ),
        preview_event_ts=(preview_bars[-1].ts.isoformat() if preview_bars else ""),
        params=params,
        runtime_params=ctx.runtime_params,
        promote=False,
    )


__all__ = [
    "AdaptiveKernelRegressionParams",
    "INDICATOR_MODULE",
    "adaptive_kernel_regression",
    "build_execution_spec",
    "build_params",
]
