from __future__ import annotations

from aef_terminal.ui.paper.config import paper_config, paper_min_rr
from aef_terminal.ui.paper.account import paper_account_payload
from aef_terminal.ui.paper.constants import (
    PAPER_ALLOWED_MIN_RR,
    PAPER_ALLOWED_SETUPS,
    PAPER_ALLOWED_SOURCES,
    PAPER_EDGE_FILTER_CACHE_SECONDS,
    PAPER_MIN_RR,
    PAPER_SKIP_INDICATOR_IDS,
    EdgeFilterLoader,
    paper_indicator_source_ids,
)
from aef_terminal.ui.paper.edge_filters import (
    paper_edge_context,
    paper_edge_filter_path,
    paper_edge_match,
    paper_load_edge_filters,
    paper_normalize_edge_rule,
)
from aef_terminal.ui.paper.execution import (
    CHART_EXECUTION_SNAPSHOT_TTL_SECONDS,
    QUOTE_EXECUTION_SNAPSHOT_TTL_SECONDS,
    PaperExecutionMetadata,
    PaperExecutionOutcome,
    PaperExecutionSubmission,
    PaperExecutionTransition,
    PaperSubmissionOutcome,
    chart_execution_price_snapshot,
    clear_execution_snapshots,
    finite_price,
    normalize_execution_snapshot,
    paper_order_execution_transition,
    quote_execution_price_snapshot,
    quote_for_route,
    route_fingerprint_key,
    record_chart_execution_snapshot,
    record_quote_execution_snapshots,
    screen_execution_price_snapshot,
    submit_paper_order_execution,
    utc_datetime,
)
from aef_terminal.ui.paper.metadata import (
    paper_payload,
    paper_payload_float,
    paper_setup_key,
    paper_setup_source_label,
    paper_signal_source_key,
    paper_trade_edge_action,
    paper_trade_enriched,
    paper_trade_session,
)
from aef_terminal.ui.paper.metrics import (
    paper_replay_summary,
    paper_trade_bucket_stats,
    paper_trade_hold_minutes,
    paper_trade_pnl_points,
    paper_trade_r_value,
    paper_trade_score,
    paper_trade_stats,
)
from aef_terminal.ui.paper.orders import (
    active_paper_orders,
    mark_order_filled,
    normalize_paper_order,
    paper_order_id,
    update_paper_order,
    utc_now_iso,
)
from aef_terminal.ui.paper.signals import (
    paper_execution_plan_rejection,
    paper_normalized_setup,
    paper_signal_rejection,
    paper_trade_from_signal,
)
from aef_terminal.ui.paper.utils import math_is_finite, paper_project_root, parse_iso_utc

__all__ = [
    "PAPER_ALLOWED_MIN_RR",
    "PAPER_ALLOWED_SETUPS",
    "PAPER_ALLOWED_SOURCES",
    "PAPER_EDGE_FILTER_CACHE_SECONDS",
    "PAPER_MIN_RR",
    "PAPER_SKIP_INDICATOR_IDS",
    "CHART_EXECUTION_SNAPSHOT_TTL_SECONDS",
    "QUOTE_EXECUTION_SNAPSHOT_TTL_SECONDS",
    "PaperExecutionMetadata",
    "PaperExecutionOutcome",
    "PaperExecutionSubmission",
    "PaperExecutionTransition",
    "PaperSubmissionOutcome",
    "EdgeFilterLoader",
    "active_paper_orders",
    "chart_execution_price_snapshot",
    "clear_execution_snapshots",
    "finite_price",
    "mark_order_filled",
    "math_is_finite",
    "normalize_execution_snapshot",
    "normalize_paper_order",
    "paper_account_payload",
    "paper_config",
    "paper_edge_context",
    "paper_edge_filter_path",
    "paper_edge_match",
    "paper_execution_plan_rejection",
    "paper_indicator_source_ids",
    "paper_load_edge_filters",
    "paper_min_rr",
    "paper_normalize_edge_rule",
    "paper_normalized_setup",
    "paper_order_id",
    "paper_order_execution_transition",
    "paper_payload",
    "paper_payload_float",
    "paper_project_root",
    "paper_replay_summary",
    "paper_setup_key",
    "paper_setup_source_label",
    "paper_signal_rejection",
    "paper_signal_source_key",
    "paper_trade_bucket_stats",
    "paper_trade_edge_action",
    "paper_trade_enriched",
    "paper_trade_from_signal",
    "paper_trade_hold_minutes",
    "paper_trade_pnl_points",
    "paper_trade_r_value",
    "paper_trade_score",
    "paper_trade_session",
    "paper_trade_stats",
    "parse_iso_utc",
    "quote_execution_price_snapshot",
    "quote_for_route",
    "route_fingerprint_key",
    "record_chart_execution_snapshot",
    "record_quote_execution_snapshots",
    "screen_execution_price_snapshot",
    "submit_paper_order_execution",
    "update_paper_order",
    "utc_datetime",
    "utc_now_iso",
]
