from __future__ import annotations

from typing import Any

from aef_terminal.indicators.control_specs import _control
from aef_terminal.indicators.module_contract import IndicatorModule, IndicatorSpec


DISCORD_SIGNALS_VERSION = "2.2-global-single-position-feed"


INDICATOR_MODULE = IndicatorModule(
    IndicatorSpec(
        "discord_signals",
        "Discord Signals",
        "typed advisory option calls projected to an exact instrument group",
        {
            "version": DISCORD_SIGNALS_VERSION,
            "series": [],
            "events": [],
            "latest": None,
            "overlays": [],
        },
        "discordSignals",
        "aef_terminal.indicators.modules.discord_signals:discord_signals_indicator",
        group="service",
        pipeline_stage="ui",
        pipeline_order=165,
        candidate_promoter="none",
        paper_tradable=False,
        custom_renderer=False,
        renderer_kind="service",
        renderer_ref="discord_signals_overlays",
        renderer_primitives=("marker", "line"),
        renderer_placements=("price",),
        service_renderer_requirements=(
            "service_router",
            "typed_external_signal_feed",
        ),
        input_contract="discord-rpc-bridge-v2",
        output_contract="discord-signal-feed-v5",
        service_payload_contract={
            "top_level": (
                "ok",
                "version",
                "mode",
                "instrument_id",
                "route_fingerprint",
                "timeframe",
                "as_of_session_date",
                "revision",
                "feed_status",
                "events",
                "positions",
                "stats",
            ),
            "event": (
                "event_id",
                "message_id",
                "channel_id",
                "reply_to_message_id",
                "ordinal",
                "published_at",
                "action",
                "context_cue",
                "parse_status",
                "reason_code",
                "source_underlying",
                "source_session_date",
                "expiry",
                "reported_dte",
                "strike",
                "option_right",
                "position_side",
                "underlying_bias",
                "reported_premium",
                "quantity",
                "sold_quantity",
                "remaining_quantity",
                "remaining_fraction",
                "stop_mode",
                "stop_value",
                "stop_basis",
                "directional_condition",
                "directional_level",
                "directional_reference",
                "directional_confirmation",
                "exit_reason",
                "reported_return_pct",
                "outcome_hint",
                "raw_content",
                "parser_version",
                "instrument_id",
                "route_fingerprint",
                "lifecycle_status",
                "position_id",
                "link_basis",
                "effective_action",
                "facts",
            ),
            "position": (
                "position_id",
                "state",
                "source_underlying",
                "source_session_date",
                "expiry",
                "reported_dte",
                "strike",
                "option_right",
                "position_side",
                "underlying_bias",
                "entry_event_id",
                "entry_at",
                "entry_premium",
                "entry_average_premium",
                "entry_average_unknown",
                "entry_legs",
                "exit_event_id",
                "exit_at",
                "exit_premium",
                "exit_reason",
                "exit_price_status",
                "exit_legs",
                "terminal_reason",
                "terminal_evidence",
                "initial_quantity",
                "remaining_quantity",
                "remaining_fraction",
                "partial_exit_size_unknown",
                "author_reported_return_pct",
                "calculated_points",
                "calculated_return_pct",
                "outcome_category",
                "pnl_direction",
                "expired_unresolved_as_of_session_date",
                "stop_updates",
                "stop_declaration_count",
                "stop_override_count",
                "stop_not_executed_count",
                "latest_stop_event_id",
                "latest_stop_mode",
                "latest_stop_value",
                "latest_stop_basis",
                "stop_execution_event_id",
                "event_ids",
            ),
            "stats": (
                "message_count",
                "event_count",
                "parsed_count",
                "ambiguous_count",
                "commentary_count",
                "directional_level_count",
                "unmatched_count",
                "open_positions",
                "closed_positions",
                "expired_unresolved_positions",
                "outcome_counts",
                "pnl_direction_counts",
                "declared_stop_positions",
                "explicit_stop_positions",
                "explicit_stop_non_execution_positions",
                "explicit_stop_non_execution_events",
                "declared_stop_without_explicit_execution",
                "stop_override_count",
                "author_reported_return_trades",
                "mean_author_reported_return_pct",
                "calculated_complete_trades",
                "mean_calculated_return_pct",
            ),
        },
        notes=(
            "Advisory data only. Source prices are author-reported, option "
            "contracts are not provider-qualified, and no event is eligible for "
            "paper or live execution."
        ),
        module_type="ui-only",
        settings_scope="instrument",
        state_key="discordSignals",
        calc_key="discordSignalsCalcEnabled",
        visible_key="discordSignalsVisible",
        chart_control_id="discord-signals-toggle",
        process_control_id="discord-signals-process",
        process_effect_ref="discord_signals_reload",
        runtime_state_ref="discord_signals_feed",
        settings_status_ref="discord_signals_connection",
        api_enabled_key="discord_signals_enabled",
        api_visible_key="discord_signals_visible",
        manager_order=165,
        runtime_order=165,
        default_calc=False,
        default_visible=True,
        overlay_collect=False,
        controls=(
            _control(
                "entries",
                "Entries",
                "toggle",
                True,
                "discordSignalsEntries",
                element_id="discord-signals-entries",
                scope="instrument",
                action="render",
                compact=False,
            ),
            _control(
                "exits",
                "Exits",
                "toggle",
                True,
                "discordSignalsExits",
                element_id="discord-signals-exits",
                scope="instrument",
                action="render",
                compact=False,
            ),
            _control(
                "trims",
                "Trims",
                "toggle",
                True,
                "discordSignalsTrims",
                element_id="discord-signals-trims",
                scope="instrument",
                action="render",
                compact=False,
            ),
            _control(
                "management",
                "Management",
                "toggle",
                False,
                "discordSignalsManagement",
                element_id="discord-signals-management",
                scope="instrument",
                action="render",
                compact=False,
            ),
            _control(
                "tradePaths",
                "Trade paths",
                "toggle",
                True,
                "discordSignalsTradePaths",
                element_id="discord-signals-trade-paths",
                scope="instrument",
                action="render",
                compact=False,
            ),
            _control(
                "directionalLevels",
                "Forecast ticks",
                "toggle",
                True,
                "discordSignalsDirectionalLevels",
                element_id="discord-signals-directional-levels",
                scope="instrument",
                action="render",
                compact=False,
            ),
            _control(
                "textSize",
                "Text size",
                "select",
                "medium",
                "discordSignalsTextSize",
                element_id="discord-signals-text-size",
                scope="instrument",
                options=("small", "medium", "large"),
                action="render",
                compact=False,
            ),
        ),
    ),
    service_ref=("aef_terminal.indicators.modules.discord_signals.service:configure_service"),
    router_ref=("aef_terminal.indicators.modules.discord_signals.service:create_router"),
    ui_js_assets=("client.js",),
)


def discord_signals_indicator(
    *_args: Any,
    **_kwargs: Any,
) -> dict[str, Any]:
    return {
        "version": DISCORD_SIGNALS_VERSION,
        "series": [],
        "events": [],
        "latest": None,
        "overlays": [],
        "status": {
            "state_code": "service",
            "mode": "ui-only",
            "preview_active": True,
        },
    }
