from __future__ import annotations

from typing import Any

from aef_terminal.indicators.control_specs import _control
from aef_terminal.indicators.module_contract import IndicatorModule, IndicatorSpec


INDICATOR_MODULE = IndicatorModule(
    IndicatorSpec(
        "tick_flow",
        "Tick Flow",
        "broker tick context service with backend delta/profile aggregates",
        {
            "version": "service-ui",
            "series": [],
            "events": [],
            "latest": None,
            "overlays": [],
        },
        "tickFlow",
        "aef_terminal.indicators.modules.tick_flow:tick_flow_indicator",
        group="service",
        pipeline_stage="ui",
        pipeline_order=95,
        candidate_promoter="none",
        paper_tradable=False,
        custom_renderer=True,
        renderer_kind="service",
        renderer_ref="tick_flow_profile",
        renderer_primitives=("tick_volume_profile", "tick_delta_labels"),
        renderer_placements=("price", "profile"),
        service_renderer_requirements=(
            "terminal_core_service",
            "broker_tick_context",
        ),
        input_contract="broker-tick-context-v1",
        output_contract="tick-flow-context-v1",
        service_payload_schema_refs=("tick_flow_context_v1",),
        shared_context_refs=("tick_flow",),
        score_family="volume",
        empirical_power=0.80,
        usefulness=1.05,
        notes=(
            "UI renderer consumes backend broker-tick aggregates only. "
            "Missing ticks remain explicitly unavailable and never fall "
            "back to candle-derived delta."
        ),
        module_type="ui-only",
        settings_scope="instrument",
        state_key="tickFlow",
        calc_key="tickFlowEnabled",
        visible_key="tickFlowVisible",
        chart_control_id="tick-flow-toggle",
        process_control_id="tick-flow-process",
        process_effect_ref="tick_flow_context",
        runtime_state_ref="tick_flow_service",
        api_enabled_key="tick_flow_enabled",
        manager_order=55,
        runtime_order=55,
        default_calc=False,
        default_visible=True,
        controls=(
            _control(
                "live",
                "Live",
                "toggle",
                False,
                "tickFlowLive",
                element_id="tick-flow-live",
                action="none",
                effect_ref="tick_flow_live",
                compact=True,
                scope="instrument",
            ),
            _control(
                "delta",
                "Delta",
                "toggle",
                True,
                "tickFlowDelta",
                element_id="tick-flow-delta",
                action="render",
                compact=True,
                scope="instrument",
            ),
            _control(
                "recentDelta",
                "Recent",
                "toggle",
                False,
                "tickFlowRecentDelta",
                element_id="tick-flow-recent-delta",
                action="render",
                effect_ref="tick_flow_recent_delta",
                compact=True,
                scope="instrument",
            ),
            _control(
                "deltaLabels",
                "Labels",
                "toggle",
                True,
                "tickFlowDeltaLabels",
                element_id="tick-flow-delta-labels",
                action="render",
                scope="instrument",
            ),
            _control(
                "profile",
                "Profile",
                "toggle",
                True,
                "tickFlowProfile",
                element_id="tick-flow-profile",
                action="render",
                scope="instrument",
            ),
            _control(
                "imbalance",
                "Imbalance",
                "toggle",
                False,
                "tickFlowImbalance",
                element_id="tick-flow-imbalance",
                action="render",
                scope="instrument",
            ),
            _control(
                "imbalanceMinVolume",
                "Imbalance min",
                "number",
                25,
                "tickFlowImbalanceMinVolume",
                element_id="tick-flow-imbalance-min-volume",
                minimum=1,
                maximum=500,
                step=1,
                action="render",
                scope="instrument",
            ),
            _control(
                "recentDeltaSeconds",
                "Recent sec",
                "number",
                30,
                "tickFlowRecentDeltaSeconds",
                element_id="tick-flow-recent-delta-seconds",
                minimum=5,
                maximum=300,
                step=5,
                action="render",
                effect_ref="tick_flow_recent_delta_seconds",
                scope="instrument",
            ),
            _control(
                "labels",
                "Labels",
                "toggle",
                False,
                "tickFlowLabels",
                element_id="tick-flow-labels",
                action="render",
                scope="instrument",
            ),
            _control(
                "lookbackMinutes",
                "Lookback",
                "number",
                120,
                "tickFlowLookback",
                element_id="tick-flow-lookback",
                minimum=60,
                maximum=360,
                step=15,
                action="load",
                effect_ref="tick_flow_context_reload",
                scope="instrument",
            ),
        ),
    ),
    ui_js_assets=("runtime.js", "overlays.js"),
)


def tick_flow_indicator(
    *_args: Any,
    **_kwargs: Any,
) -> dict[str, Any]:
    return {
        "version": "service-ui",
        "series": [],
        "events": [],
        "latest": None,
        "overlays": [],
        "status": {
            "state_code": "service",
            "mode": "ui-only",
            "preview_active": True,
        },
    }
